permalink: '/:categories/:year/:month/:day/:title'
exclude:
  - .rvmrc
  - .rbenv-version
  - README.md
  - Rakefile
  - changelog.md
pygments: false
markdown: kramdown
extensions:
  - fenced_code_blocks
excerpt_separator: <!--more-->
url: ''
baseurl: ''
data-ad-slot: null
data-ad-client: null
google_ad_client: null
post_limit: 5
title: fullit
tagline: A responsive templeate built for jekyll3
author:
  name: fullit
  email: lantoniotrento@gmail.com
  github: antoniotrento
  twitter: lantoniotrento
  feedburner: fullit
twitter_username: lantoniotrento
production_url: 'https://fullit.github.io'
JB:
  version: 0.3.0
  BASE_PATH: 'https://fullit.github.io'
  ASSET_PATH: 'https://fullit.github.io/assets/themes/bootstrap'
  archive_path: /archive.html
  categories_path: /categories.html
  tags_path: /tags.html
  atom_path: /atom.xml
  rss_path: /rss.xml
  comments:
    provider: disqus
    disqus:
      short_name: null
      num_posts: 5
      width: 580
      colorscheme: light
  analytics:
    provider: google
    google:
      tracking_id: ''
  sharing:
    provider: false
